config/routes.rb
Rails.application.routes.draw do
  #get 'posts/search', to: 'posts#search'
  devise_for :users, controllers: {
  omniauth_callbacks: "omniauth_callbacks"
}
  resources :posts do
    get 'search', :on => :collection
  end
  resources :schedules, except: :new
  get 'users/calendar'
  root 'home#index'
  resources :users
  get '/schedules/:newdate/new/', to: 'schedules#new', as: 'new_schedule'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    validates :datetime, presence: true
    validates :task, presence: true
    validates :importanceoftask, presence: true

    validate :date_before_start

    def date_before_start
        return if datetime.blank? 
        errors.add(:datetime,"は今日以降のものを選択してください")if datetime < Date.today
    end
        
    



end

app/models/schedule.rb
class Schedule < ApplicationRecord
    belongs_to :user
    
    def self.schedule_destroy
        time = Time.now 
        schedules = Schedule.all
            if schedules.start_time < time
                schedules.destroy
            end

    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable,
          :omniauthable, omniauth_providers: %i[line]
  has_many :posts 
  has_many :schedules

  def social_profile(provider)
    social_profiles.select { |sp| sp.provider == provider.to_s }.first
  end

  def set_values(omniauth)
    return if provider.to_s != omniauth["provider"].to_s || uid != omniauth["uid"]
    credentials = omniauth["credentials"]
    info = omniauth["info"]

    access_token = credentials["refresh_token"]
    access_secret = credentials["secret"]
    credentials = credentials.to_json
    name = info["name"]
    # self.set_values_by_raw_info(omniauth['extra']['raw_info'])
  end

  def set_values_by_raw_info(raw_info)
    self.raw_info = raw_info.to_json
    self.save!
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery :except => [:create]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

def index
end

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def line; basic_action end

    private
    def basic_action
      @omniauth = request.env["omniauth.auth"]
      if @omniauth.present?
        @profile = User.find_or_initialize_by(provider: @omniauth["provider"], uid: @omniauth["uid"])
        if @profile.email.blank?
          email = @omniauth["info"]["email"] ? @omniauth["info"]["email"] : "#{@omniauth["uid"]}-#{@omniauth["provider"]}@example.com"
          @profile = current_user || User.create!(provider: @omniauth["provider"], uid: @omniauth["uid"], email: email, name: @omniauth["info"]["name"], password: Devise.friendly_token[0, 20])
        end
        @profile.set_values(@omniauth)
        sign_in(:user, @profile)
      end
      flash[:notice] = "ログインしました"
      redirect_to root_path
    end
  
    def fake_email(uid, provider)
      "#{auth.uid}-#{auth.provider}@example.com"
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    before_action :authenticate_user!

    def index
        #if params[:search] == nil
            #@posts = Post.all.order(datetime: :asc).limit(5)
            #@schedules = Schedule.order(start_time: :asc).limit(3)
            @post = Post.new
            @posts = Post.where(user_id:current_user.id).order(datetime: :asc).limit(5)
            @schedules = Schedule.where(user_id:current_user.id).order(start_time: :asc).limit(3)
            # elsif params[:search] == ''
            #@posts = Post.all.order(datetime: :asc).limit(5)
            #@schedules = Schedule.order(start_time: :asc).limit(3)
            #@post = Post.new
            #else
            #@schedules = Schedule.order(start_time: :asc).limit(3)
            #@posts = Post.where("task LIKE ? ",'%' + params[:search] + '%')
            #@post = Post.new
        #end
    end

    def new
        @post = Post.new
        @schedule =Schedule.new
    end

    def calendar
        @events = Post.all
    end

    def create
        post = Post.new(post_params)
        post.user_id = current_user.id
        post.user_uid = current_user.uid
        post.save
        #@posts = Post.all.order(datetime: :asc).limit(5)
        @posts = Post.where(user_id:current_user.id).order(datetime: :asc).limit(5)
            
        

    end

    def show
        @post = Post.find(params[:id])
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        # binding pry
        post=Post.find(params[:id])
        post.update(post_params)
        post.save
        #@posts = Post.all.order(datetime: :asc).limit(5)
        @posts = Post.where(user_id:current_user.id).order(datetime: :asc).limit(5)

    
    end

    def destroy
        post = Post.find(params[:id])
        post.destroy
        #@posts =Post.all.order(datetime: :asc).limit(5)
        @posts = Post.where(user_id:current_user.id).order(datetime: :asc).limit(5)

    end

    def search
        if params[:search] == nil
            @posts= Post.all
        elsif params[:search] == ''
            @Posts= Post.all
        else
            @posts = Post.where("task LIKE ?", '%' + params[:search] + '%')
        end
        redirect_to request.referer
    end


    private
    def post_params
    params.require(:post).permit(:task, :datetime, :importanceoftask,)
    end



end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController



    def new
        @schedule =Schedule.new
        @schedule.start_time=params[:newdate]
    end
    
    def create
        schedule = Schedule.new(schedule_params)
        schedule.user_id = current_user.id
        schedule.user_uid = current_user.uid
        schedule.save
        @schedules = current_user.schedules
        @user = current_user
    end

    def show
        @schedule = Schedule.find(params[:id])
    end

    def edit
        @schedule = Schedule.find(params[:id])
    end

    def destroy
        schedule = Schedule.find(params[:id])
        schedule.destroy
        #@schedules = Schedule.all.order(datetime: :asc).limit(3)
        @schedules = Schedule.where(user_id:current_user.id).order(start_time: :asc).limit(3)
        @users = User.find(current_user.id)
    end

    def update
        schedule = Schedule.find(params[:id])
        schedule.update(schedule_params)
        schedule.save
        @schedules = Schedule.where(user_id:current_user.id)
        #@schedules = Schedule.all.order(datetime: :asc).limit(3)
    end

    private
    def schedule_params
    params.require(:schedule).permit(:title, :content, :start_time)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


    def show
        @user = User.find(current_user.id) 
        @schedules = @user.schedules
    end





    private
    def schedule_params
        params.require(:schedule).permit(:title, :content, :start_time )
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<%= stylesheet_link_tag "home", :media => "all"%>
<body>
        <div class="main-contents">
            <a class="btn btn-success btn-lg" href="/posts">ログイン</a>
            <a class="btn btn-success btn-lg" href="/users/sign_up">新規登録</a>
        </div>

</body>
    

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>Syaflack</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">


  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light" style="background-color:#66FF66;",>
      <div class="container-fluid">
      <h1 class="m-0">
      <a class="navbar-brand" href="/posts" style = "color:#FFFFFF; font-size:xx-large; font-weight:bold;" >Syaflack</a>
      </h1>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in?%>
        <li class="nav-item m-1">
        <a class="nav-link active" aria-current="page"><%= link_to "マイページへ", user_path(current_user.id), class:'btn btn-success'%></a>
        </li>
        <li class="nav-item m-1"> 
          <a class="nav-link active" aria-current="page"><%= link_to "ログアウト" , destroy_user_session_path, method: :delete, class:'btn btn-success'  %></a>
        </li>
      </ul>

        <form class="d-flex">
        <%= form_tag(search_posts_path, method: :get,remote:true) do %>
          <%= text_field_tag :search,nil,placeholder:'キーワードを入力',class:"form-control"%>
          <%= submit_tag '検索する',class:"btn btn-success" ,id:"search-button"%>
        <% end %>
        </form>
        <% end %>
    </div>
  </div>
</nav>
    </header>

    <main>
        <%= yield %>
    </main>

    <footer style = "background-color:#92f097;">
    <p> For all Socially incompatible, Created by Taichi Watanabe, Special thanks GeekSalon Kyoto </p>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
  </body>
  
</html>

app/views/posts/_edit.html.erb
<div class="modal fade" id="staticBackdrop2" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">詳細</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
　　　<%= form_for @post, remote: true do |form| %>
      <div class="modal-body">
        <br>
          <div class="form-group">
          <%= form.text_field :task,size:55, class:"form-control"%>
          </div>
        <br>

          <div class="form-group">
          <%= form.select :importanceoftask, [["高", "高"], ["中", "中"], ["低", "低"]] ,{ include_blank:"重要度"},{class:'form-control', required: true}%>
          </div>

        <br>
            <div class="form-group">
          <%= label :datetime, "期限" %>
          <%= form.datetime_field :datetime,size:140, class:"form-control", required:true %>
          </div>
        <br>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary btn-lg" data-bs-dismiss="modal">キャンセル</button>
        <%= form.submit "編集する", class: "btn-primary btn-lg" %>
　　　　
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/_posts.html.erb

<body>
        <% posts.each do |t| %>

            <% if user_signed_in? && current_user.id == t.user_id %>  

<div class="card text-center col-5 m-lg-auto">
  <div class="card-header" style="font-size: x-large; font-weight:bold; background-color:#66FF66">
    <span class = "badge bg-success"><%= t.importanceoftask %></span>    
  </div>
  <div class="card-body m-md-2">
    <h3 class="card-title m-md-4"><%= t.task %></h3>
    <%= link_to "編集する", edit_post_path(t.id), class: "btn-primary btn-lg", data:{remote: true}, style: "text-decoration: none;" %>
    <%= link_to "達成！", post_path(t.id), method: :delete, data: { confirm: '本当に削除しますか？',remote:true} , class: "btn-danger btn-lg", style: "text-decoration: none;"%>　
  </div>
  <div class="card-footer text-muted" style="font-size: x-large; font-weight:bold; background-color:#66FF66; color:#000000;">
  <%= t.datetime&.strftime("%Y年%m月%d日%H時%M分") %>
  </div>
</div>
        <% end %>
        <% end %>
        <div class="modal fade" id="s-modal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">検索結果</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
    <div class="modal-body">
            <% posts.each do |t| %>

        <div class="card text-center col-12 m-lg-auto">
            <div class="card-header" style="font-size: x-large; font-weight:bold; background-color:#66FF66">
            <span class = "badge bg-success"><%= t.importanceoftask %></span>    
            </div>
                <div class="card-body m-md-2">
                <h3 class="card-title m-md-4"><%= t.task %></h3>
                    <%= link_to "編集する", edit_post_path(t.id), class: "btn-primary btn-lg", data:{remote: true}, style: "text-decoration: none;" %>
                    <%= link_to "達成！", post_path(t.id), method: :delete, data: { confirm: '本当に削除しますか？',remote:true} , class: "btn-danger btn-lg", style: "text-decoration: none;"%>　
                </div>
                <div class="card-footer text-muted" style="font-size: x-large; font-weight:bold; background-color:#66FF66; color:#000000;">
                    <%= t.datetime&.strftime("%Y年%m月%d日%H時%M分") %>
                </div>
        </div>
            <% end %>
    </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">閉じる</button>
      </div>
    </div>
  </div>
</div>
</body>

app/views/posts/_schedules.html.erb
    <ul class="list-group list-group-horizontal m-md-auto">
        <% @schedules.each do |t| %>
            <% if user_signed_in? && current_user.id == t.user_id %>  
    <li class="list-group-item list-group-item-action list-group-item-success flex-fill"><%= link_to t.title, schedule_path(t.id), data:{remote:true}, style: "text-decoration: none; display:block;" %></li>
            <% end %>
        <% end %>
    </ul>

app/views/posts/_search.html.erb
<div class="modal fade" id="s-modal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">検索結果</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
    <div class="modal-body">
            <% posts.each do |t| %>

        <div class="card text-center col-12 m-lg-auto">
            <div class="card-header" style="font-size: x-large; font-weight:bold; background-color:#66FF66">
            <span class = "badge bg-success"><%= t.importanceoftask %></span>    
            </div>
                <div class="card-body m-md-2">
                <h3 class="card-title m-md-4"><%= t.task %></h3>
                    <%= link_to "編集する", edit_post_path(t.id), class: "btn-primary btn-lg", data:{remote: true}, style: "text-decoration: none;" %>
                    <%= link_to "達成！", post_path(t.id), method: :delete, data: { confirm: '本当に削除しますか？',remote:true} , class: "btn-danger btn-lg", style: "text-decoration: none;"%>　
                </div>
                <div class="card-footer text-muted" style="font-size: x-large; font-weight:bold; background-color:#66FF66; color:#000000;">
                    <%= t.datetime&.strftime("%Y年%m月%d日%H時%M分") %>
                </div>
        </div>
            <% end %>
    </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">閉じる</button>
      </div>
    </div>
  </div>
</div>

app/views/posts/create.js.erb
$("textarea").val("");
$("input").val("");
$('#staticBackdrop').modal('hide');
$('#alltasks').html("<%= escape_javascript(render 'posts', posts: @posts) %>");
$('body').removeClass('modal-open');
$('.modal-backdrop').remove();

app/views/posts/destroy.js.erb
$('#alltasks').html("<%= escape_javascript(render 'posts', posts: @posts) %>");

app/views/posts/edit.js.erb
$('#editmodal').html("<%= escape_javascript(render 'edit')%>");
$('#staticBackdrop2').modal('show');

app/views/posts/index.html.erb
<%= stylesheet_link_tag "post.index", :media => "all" %>

<div id = "searchmodal"></div>
<div id = "editmodal"></div>
<div id = "showschedule"></div>
<body>
    <div class = "container">

    <br>
    
    <h4>直近のイベント</h4>
    <div id="allschedules">
    <%= render 'schedules', schedules: @schedules %>
    </div>
    <br>

    </div>
    

<div class = "container mt-2">
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
  新しいタスク
</button>
</div>

<div class = "container mt-2">
<h3>やること一覧</h3>
</div>

<div id="alltasks">
  <%= render 'posts', posts: @posts %>
</div>

<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">新しいタスク</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
　　　<%= form_for @post, remote: true do |form| %>
      <div class="modal-body">

          <br>
          <div class="form-group form-floating">
          <%= form.text_field :task,size:55, class:"form-control", placeholder:"新しい課題",id:"floatingInput" ,required:true%>
          <label for="floatingInput">新しい課題</label>
          </div>
          
          <br>

          <div class="form-group">
          <%= form.select :importanceoftask, [["高", "高"], ["中", "中"], ["低", "低"]] ,{ include_blank:"重要度"},{class:'form-control', required: true}%>
          </div>
    
          <br>

          <div class="form-group">
          <%= label :datetime, "期限" %>
          <%= form.datetime_field :datetime, class:"form-control", required:true %>
          </div>
          
          <br>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary btn-lg" data-bs-dismiss="modal">キャンセル</button>
        <%= form.submit "追加する", class: "btn-primary btn-lg" %>
      </div>
      <% end %>
    </div>
  </div>
</div>    
</body>


app/views/posts/index.js.erb
$('#searchmodal').html("<%= escape_javascript(render 'search', posts:@posts)%>");
$('#s-modal').modal('show');

app/views/posts/search.html.erb
<script>
          $("#search-button").click(function(){
                  $('#searchmodal').html("<%= escape_javascript(render 'search', posts:@posts)%>");
                  $('#s-modal').modal('show');
          })
          </script>
          <%= link_to '検索する', search_posts_path, class:"btn btn-success", data: {remote:true}  %>

app/views/posts/search.js.erb
$('#searchmodal').html("<%= escape_javascript(render 'posts', posts:@posts)%>");
$('#s-modal').modal('show');

app/views/posts/update.js.erb
$('#staticBackdrop2').modal('hide');
$('#alltasks').html("<%= escape_javascript(render 'posts', posts: @posts) %>");

app/views/schedules/_edit.html.erb
<div class="modal fade" id="staticBackdrop1" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">詳細</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>



            <%= form_for @schedule, remote:true do |form| %>
            <div class="modal-body">

                <br>
    
                <div class="form-group form-floating">
                <%= form.text_field :title, class:"form-control",placeholder:"タイトル",id:"floatingInput" ,required:true%>
                <label for="floatingInput">イベント</label>
                </div>

　　　　　　　　　<br>

                <div class="form-group form-floating">
                <%= form.text_area :content, class:"form-control",placeholder:"内容",id:"floatingInput" ,required:true%>
                <label for="floatingInput">内容</label>
                </div>

                <br>

                <div class="form-group">
                <%= label :start_time, "日時" %>
                <br>
                <%= form.time_select :start_time,{},{class:"form-control",style:'display: inline-block; width:auto;'}%>
                </div>

                <br>

                
            </div>


      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">閉じる</button>
                <%= form.submit "完了", class: "btn btn-primary" %>
                <%= link_to "削除", schedule_path(@schedule.id), method: :delete, data: { confirm: '本当に削除しますか？',remote:true} , class: "btn btn-danger", style: "text-decoration: none;"%>　
      </div>
                <% end %>

    </div>
  </div>
</div>

app/views/schedules/_new.html.erb
<div class="modal fade" id="staticBackdrop1" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">新規イベント</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>



            <%= form_for @schedule, remote:true do |form| %>
            <div class="modal-body">

                <br>
    
                <div class="form-group form-floating">
                <%= form.text_field :title, class:"form-control",placeholder:"タイトル",id:"floatingInput" ,required:true%>
                <label for="floatingInput">イベント</label>
                </div>

　　　　　　　　　<br>

                <div class="form-group form-floating">
                <%= form.text_area :content, class:"form-control",placeholder:"内容",id:"floatingInput" ,required:true%>
                <label for="floatingInput">内容</label>
                </div>

                <br>

                <div class="form-group">
                <%= label :start_time, "日時" %>
                <br>
                <%= form.time_select :start_time,{},{class:"form-control",style:'display: inline-block; width:auto;'}%>
                </div>

                <br>

                
            </div>


      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">閉じる</button>
                <%= form.submit "追加する", class: "btn btn-primary" %>
      </div>
                <% end %>

    </div>
  </div>
</div>

app/views/schedules/_show.html.erb
<!-- モーダルの設定 -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">イベントの詳細</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="閉じる"></button>
      </div>
      <div class="modal-body">
      <p>
  <strong>タイトル</strong>
  <%= @schedule.title %>
</p>

<p>
  <strong>内容</strong>
  <%= @schedule.content %>
</p>

<p>
  <strong>日時</strong>
  <%= @schedule.start_time.strftime("%Y年%m月%d日%H時%M分") %>
</p>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary btn-lg" data-bs-dismiss="modal">閉じる</button>
        <%= link_to '削除', schedule_path(@schedule.id), method: :delete, data: { confirm: '本当に?', remote:true}, class:"btn-danger btn-lg", style: "text-decoration: none;"%>
      </div><!-- /.modal-footer -->
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/schedules/create.js.erb
$("text_area").val("");
$("input").val("");
$('#staticBackdrop1').modal('hide');
$('#userevents').html("<%= escape_javascript(render 'users/events', {user: @user, schedules:@schedules}) %>");

app/views/users/_events.html.erb
<div class = "calender">
    <%= month_calendar events: schedules.each do |date, schedules| %>
        <div class = "date">
            <div class = "table m-4">
                <%= link_to date.day, new_schedule_path(date), class: "date-btn", data:{remote: true}, style: "text-decoration: none; display: block;
    width: 100%; height: 100%;" %>
            </div>
        </div>
        

        <% schedules.each do |schedules| %>
            <% if user_signed_in? && current_user.id == schedules.user_id %>  
            <div style = "display:flex;">
            <%= link_to schedules.title, edit_schedule_path(schedules.id), data:{remote:true}, style: "text-decoration: none;" %>
            </div>
            <%end%>
        <%end%>
        
    <%end%>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>